import {brushCategories,defaultBrushes,getBrushStamp,presetToSettings,validateBrushes} from "./brushEngine.js";
import type {BrushPreset,BrushSettings} from "./types.js";

const CUSTOM_KEY="sogsketch-brushes-v3",FAVOURITES_KEY="sogsketch-brush-favourites-v3",RECENT_KEY="sogsketch-recent-brushes-v3",OPEN_KEY="sogsketch-brush-library-open";
const byId=(id:string,items:BrushPreset[]):BrushPreset|undefined=>items.find(item=>item.id===id);

export class BrushLibrary{
 private custom:BrushPreset[]=[];private favourites=new Set<string>();private recent:string[]=[];private activeId="hard-round";private filter="All";private favouritesOnly=false;private recentOnly=false;
 constructor(private getSettings:()=>BrushSettings,private applySettings:(settings:BrushSettings)=>void,private onSelect?:(preset:BrushPreset)=>void){this.load();this.bind();const selected=this.active;if(selected){this.applySettings(presetToSettings(selected,this.getSettings()));this.onSelect?.(selected)}this.render();if(localStorage.getItem(OPEN_KEY)==="true")this.setOpen(true)}
 get all():BrushPreset[]{return[...defaultBrushes,...this.custom]}
 get active():BrushPreset|undefined{return byId(this.activeId,this.all)}
 selectById(id:string):void{const preset=byId(id,this.all);if(preset)this.select(preset)}
 private load():void{try{this.custom=JSON.parse(localStorage.getItem(CUSTOM_KEY)??"[]") as BrushPreset[]}catch{this.custom=[]}try{this.favourites=new Set(JSON.parse(localStorage.getItem(FAVOURITES_KEY)??"[]") as string[])}catch{this.favourites=new Set()}try{this.recent=JSON.parse(localStorage.getItem(RECENT_KEY)??"[]") as string[]}catch{this.recent=[]}const saved=localStorage.getItem("sogsketch-active-brush");this.activeId=saved&&byId(saved,this.all)?saved:"hard-round";localStorage.setItem("sogsketch-active-brush",this.activeId)}
 private save():void{localStorage.setItem(CUSTOM_KEY,JSON.stringify(this.custom));localStorage.setItem(FAVOURITES_KEY,JSON.stringify([...this.favourites]));localStorage.setItem(RECENT_KEY,JSON.stringify(this.recent));localStorage.setItem("sogsketch-active-brush",this.activeId)}
 setOpen(open:boolean):void{const panel=document.querySelector<HTMLElement>("#brushLibrary")!,button=document.querySelector<HTMLButtonElement>("#openBrushLibrary")!;panel.classList.toggle("open",open);panel.setAttribute("aria-hidden",String(!open));button.setAttribute("aria-expanded",String(open));button.textContent=open?"Close Brush Library":"Open Brush Library";localStorage.setItem(OPEN_KEY,String(open))}
 toggle():void{this.setOpen(!document.querySelector("#brushLibrary")?.classList.contains("open"))}
 syncSettings():void{document.querySelectorAll<HTMLInputElement|HTMLSelectElement>("[data-brush-setting]").forEach(input=>{const key=input.dataset.brushSetting as keyof BrushSettings;const value=this.getSettings()[key];input.value=String(value);const output=document.querySelector<HTMLOutputElement>(`[data-brush-output="${key}"]`);if(output)output.value=typeof value==="number"?`${value}${key==="size"?"px":key==="rotation"||key==="angle"?"°":"%"}`:String(value)});this.drawMainPreview(this.active?.name??"Custom brush")}
 private bind():void{document.querySelector("#openBrushLibrary")!.addEventListener("click",()=>this.toggle());document.querySelector("#closeBrushLibrary")!.addEventListener("click",()=>this.setOpen(false));const category=document.querySelector<HTMLSelectElement>("#brushCategory")!;for(const value of brushCategories){const option=document.createElement("option");option.value=option.textContent=value;category.append(option)}category.addEventListener("change",()=>{this.filter=category.value;this.favouritesOnly=this.recentOnly=false;this.render()});document.querySelector<HTMLInputElement>("#brushSearch")!.addEventListener("input",()=>this.render());document.querySelector("#showFavourites")!.addEventListener("click",()=>{this.favouritesOnly=!this.favouritesOnly;this.recentOnly=false;this.render()});document.querySelector("#showRecent")!.addEventListener("click",()=>{this.recentOnly=!this.recentOnly;this.favouritesOnly=false;this.render()});document.querySelectorAll<HTMLInputElement|HTMLSelectElement>("[data-brush-setting]").forEach(input=>input.addEventListener("input",()=>{const settings={...this.getSettings()},key=input.dataset.brushSetting as keyof BrushSettings;(settings as unknown as Record<string,string|number>)[key]=input instanceof HTMLInputElement?Number(input.value):input.value;this.applySettings(settings);this.syncSettings()}));document.querySelector("#newBrushPreset")!.addEventListener("click",()=>this.saveCurrent());document.querySelector("#duplicateBrushPreset")!.addEventListener("click",()=>this.duplicate());document.querySelector("#renameBrushPreset")!.addEventListener("click",()=>this.rename());document.querySelector("#deleteBrushPreset")!.addEventListener("click",()=>this.delete());document.querySelector("#resetBrushPresets")!.addEventListener("click",()=>this.reset());document.querySelector("#exportBrushPresets")!.addEventListener("click",()=>this.export());const input=document.querySelector<HTMLInputElement>("#brushPresetFileInput")!;document.querySelector("#importBrushPresets")!.addEventListener("click",()=>input.click());input.addEventListener("change",()=>{const file=input.files?.[0];if(file)void this.import(file);input.value=""})}
 private select(preset:BrushPreset):void{this.activeId=preset.id;this.recent=[preset.id,...this.recent.filter(id=>id!==preset.id)].slice(0,12);this.save();this.applySettings(presetToSettings(preset,this.getSettings()));this.onSelect?.(preset);this.render();this.syncSettings()}
 private visible():BrushPreset[]{const search=document.querySelector<HTMLInputElement>("#brushSearch")?.value.trim().toLowerCase()??"";let result=this.all.filter(item=>(this.filter==="All"||item.category===this.filter)&&(!search||`${item.name} ${item.category}`.toLowerCase().includes(search)));if(this.favouritesOnly)result=result.filter(item=>this.favourites.has(item.id));if(this.recentOnly)result=this.recent.map(id=>byId(id,result)).filter((item):item is BrushPreset=>Boolean(item));return result}
 render():void{const grid=document.querySelector<HTMLElement>("#brushLibraryGrid")!;document.querySelector("#showFavourites")?.classList.toggle("active",this.favouritesOnly);document.querySelector("#showRecent")?.classList.toggle("active",this.recentOnly);grid.replaceChildren(...this.visible().map(preset=>{const button=document.createElement("div");button.className=`library-brush${preset.id===this.activeId?" active":""}`;button.title=`${preset.name} — ${preset.category}`;button.tabIndex=0;button.setAttribute("role","button");const canvas=document.createElement("canvas");canvas.width=108;canvas.height=80;this.drawPreview(canvas,preset);const label=document.createElement("span");label.innerHTML=`${preset.name}<small>${preset.category}</small>`;const star=document.createElement("button");star.className=`favourite${this.favourites.has(preset.id)?" active":""}`;star.textContent="★";star.title=`${this.favourites.has(preset.id)?"Remove from":"Add to"} favourites`;star.addEventListener("click",event=>{event.stopPropagation();this.favourites.has(preset.id)?this.favourites.delete(preset.id):this.favourites.add(preset.id);this.save();this.render()});button.append(canvas,label,star);button.addEventListener("click",()=>this.select(preset));button.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();this.select(preset)}});button.addEventListener("pointerenter",()=>this.drawMainPreview(preset.name,preset));button.addEventListener("focus",()=>this.drawMainPreview(preset.name,preset));return button}));this.syncSettings()}
 private drawPreview(canvas:HTMLCanvasElement,preset:BrushPreset):void{const ctx=canvas.getContext("2d")!;ctx.clearRect(0,0,canvas.width,canvas.height);const settings=presetToSettings(preset,this.getSettings()),size=Math.min(28,Math.max(3,preset.size*.28)),isEffect=["scatter","leaf","grass","cloud"].includes(preset.tip);ctx.strokeStyle="#e6e6e6";ctx.fillStyle="#e6e6e6";ctx.globalAlpha=Math.max(.32,preset.opacity/100);if(isEffect){const stamp=getBrushStamp(settings,"#e6e6e6",size);for(let x=12;x<canvas.width-8;x+=Math.max(8,size*preset.spacing/70)){const y=canvas.height/2+Math.sin(x/18)*10;ctx.save();ctx.translate(x,y);ctx.rotate((preset.angle+preset.rotation+x)*Math.PI/180);ctx.drawImage(stamp,-stamp.width/2,-stamp.height/2);ctx.restore()}return}ctx.lineCap=preset.tip==="flat"||preset.tip==="chisel"?"square":"round";ctx.lineJoin="round";ctx.lineWidth=preset.tip==="chisel"?size*.35:preset.tip==="flat"?size*.72:size;if(preset.hardness<35){ctx.shadowColor="#e6e6e6";ctx.shadowBlur=size*(1-preset.hardness/100)*.55;ctx.globalAlpha*=.55}ctx.beginPath();ctx.moveTo(8,canvas.height*.62);ctx.bezierCurveTo(canvas.width*.28,canvas.height*.12,canvas.width*.62,canvas.height*.9,canvas.width-8,canvas.height*.35);ctx.stroke();if(preset.tip==="bristle"||preset.texture!=="none"){ctx.shadowBlur=0;ctx.globalAlpha=.22;ctx.lineWidth=Math.max(.5,size/8);for(let offset=-2;offset<=2;offset++){ctx.beginPath();ctx.moveTo(8,canvas.height*.62+offset*2);ctx.bezierCurveTo(canvas.width*.28,canvas.height*.12+offset*2,canvas.width*.62,canvas.height*.9+offset*2,canvas.width-8,canvas.height*.35+offset*2);ctx.stroke()}}}
 private drawMainPreview(name:string,preset=this.active):void{const canvas=document.querySelector<HTMLCanvasElement>("#libraryBrushPreview");if(!canvas)return;const effective=preset??({...this.getSettings(),id:"current",name,category:"Custom"} as BrushPreset);this.drawPreview(canvas,effective);document.querySelector<HTMLElement>("#libraryPreviewName")!.textContent=name}
 private currentPreset(name:string,id=crypto.randomUUID()):BrushPreset{return{id,name,category:"Custom",custom:true,...this.getSettings(),eraserMode:undefined,symmetry:undefined} as unknown as BrushPreset}
 saveCurrent():void{const name=prompt("Brush name","Custom Brush")?.trim();if(!name)return;const preset=this.currentPreset(name);this.custom.push(preset);this.activeId=preset.id;this.save();this.render()}
 private duplicate():void{const source=this.active;const name=prompt("Duplicate brush as",`${source?.name??"Brush"} copy`)?.trim();if(!name)return;const preset={...(source??this.currentPreset(name)),id:crypto.randomUUID(),name,category:"Custom" as const,custom:true};this.custom.push(preset);this.activeId=preset.id;this.save();this.render()}
 private rename():void{const preset=this.custom.find(item=>item.id===this.activeId);if(!preset){alert("Default brushes cannot be renamed. Duplicate it first.");return}const name=prompt("Brush name",preset.name)?.trim();if(name){preset.name=name;this.save();this.render()}}
 private delete():void{const index=this.custom.findIndex(item=>item.id===this.activeId);if(index<0){alert("Default brushes always remain available.");return}if(!confirm(`Delete ${this.custom[index]!.name}?`))return;this.custom.splice(index,1);this.activeId="hard-round";this.save();this.selectById(this.activeId)}
 private reset():void{const preset=byId(this.activeId,defaultBrushes)??defaultBrushes.find(item=>item.id==="hard-round")!;this.select(preset)}
 private export():void{const blob=new Blob([JSON.stringify({format:"sogsketch-brushes",version:1,brushes:this.custom},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="sogsketch-brushes.json";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 private async import(file:File):Promise<void>{try{const parsed=JSON.parse(await file.text()) as {brushes?:BrushPreset[]}|BrushPreset[],brushes=Array.isArray(parsed)?parsed:parsed.brushes??[],errors=validateBrushes(brushes);if(errors.length)throw new Error(errors.join("\n"));this.custom.push(...brushes.map(item=>({...item,id:crypto.randomUUID(),category:"Custom" as const,custom:true})));this.save();this.render()}catch(error){alert(`Could not import brushes: ${String(error)}`)}}
}
